@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault 

package bryanthedragon.mclibreloaded.permissions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;